backend:
  name: github
  repo: ToutUnEsprit/toutunesprit
media_folder: static/assets
public_folder: assets
collections:
  - name: Contenu
    label: Contenu
    folder: "/src/content"
    create: true
    fields:
      - { name: title, label: Titre }
      - { name: categorie, label: Catégorie , widget: "select",
          options:
            [
              "Thé",
              "Café",
              "Infusion",
              "Accessoire",
              "Épicerie",
              
            ]}
      - { name: img, label: Image (lien)}
      - { name: img, label: Image, widget: "image", required: false,}
      - {
          name: sous-categorie,
          label: Sous-Catégorie,
          multipe: true,
          , widget: "select",
          options:
            [
              "Thé vert",
              "Thé noir",
              "Thé blanc",
              "Thé fumé",
              "Thé blend",
              "Rooibos",
              "Oolong",
              "Café",
              "Infusion",
              "Autre"
            ],
        }
      - { name: description, label: Description }
      - { name: composition, label: Composition , required: false,}
      - { name: temps, label: Temps d'infusion , required: false,}
      - { name: degree, label: Température d'infusion,  required: false, widget: "select",
          options:
          [ "65°C",
              "70°C",
              "75°C",
              "80°C",
              "85°C",
              "90°C",
              "95°C",
              "100°C"
            ]}
      - { name: time, label: Quand le déguster, widget: "select" ,required: false,
          options:
            [
              "Matin",
              "Après-Midi",
              "Soir",
              "Toute la journée",
              "Matin, Après-midi",
              
            ]}
